name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            arch: intel
            runs_on: macos-13
          - target: aarch64-apple-darwin
            arch: arm64
            runs_on: macos-14
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm tauri build --bundles dmg --target ${{ matrix.target }}

      - name: Rename DMG file
        run: |
          cd src-tauri/target/${{ matrix.target }}/release/bundle/dmg
          DMG_FILE=$(ls *.dmg | head -n 1)
          VERSION=${GITHUB_REF#refs/tags/v}
          NEW_NAME="kill-process_${VERSION}_${{ matrix.arch }}.dmg"
          mv "$DMG_FILE" "$NEW_NAME"
          echo "Renamed $DMG_FILE to $NEW_NAME"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kill-process-macos-${{ matrix.arch }}
          path: src-tauri/target/${{ matrix.target }}/release/bundle/dmg/*.dmg
          retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*.dmg
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## Installation Instructions (macOS)
            
            Since this app is not notarized by Apple, macOS may show a "damaged app" warning. Please follow these steps:
            
            ### Method 1: Through System Preferences
            1. Download and double-click the DMG file
            2. If you see a "damaged" warning, click "Cancel" (don't move to trash)
            3. Open "System Preferences" > "Security & Privacy" > "General"
            4. Click "Open Anyway" (if you see the prompt)
            5. Or right-click the app > "Open" > "Open"
            
            ### Method 2: Remove quarantine attribute via Terminal
            ```bash
            sudo xattr -rd com.apple.quarantine /Applications/kill-process.app
            ```
            
            ### Architecture Notes
            - `intel.dmg`: For Intel Macs (x86_64)
            - `arm64.dmg`: For Apple Silicon Macs (M1/M2/M3)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 